#!/usr/bin/env python3
"""从库内型号尾部高频词挖掘候选色名，追加到 data/luxury_color_lexicon.txt。

用法:
  python3 scripts/build_color_lexicon.py --dry-run   # 仅预览
  python3 scripts/build_color_lexicon.py             # 追加新词（不重复）
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.config import load_config
from src.db import db_session
from src.luxury_colors import luxury_color_lexicon
from src.product_format import _is_size_token

LEXICON_PATH = ROOT / "data" / "luxury_color_lexicon.txt"
REPORT_PATH = ROOT / "data" / "mined_color_candidates.txt"

# 明显不是颜色的尾部词（款式/材质/品类/包型线）
_SKIP_TAIL = frozenset(
    {
        "wallet",
        "necklace",
        "earrings",
        "earring",
        "bracelet",
        "ring",
        "watch",
        "sneakers",
        "flats",
        "mules",
        "scarf",
        "shawl",
        "hat",
        "case",
        "chain",
        "canvas",
        "leather",
        "patent",
        "suede",
        "nappa",
        "vache",
        "taurillon",
        "edition",
        "limited",
        "christmas",
        "animation",
        "roller",
        "coaster",
        "party",
        "garden",
        "country",
        "pochette",
        "neverfull",
        "delightful",
        "graceful",
        "evelyne",
        "amazone",
        "marcheline",
        "victorine",
        "neo",
        "pouch",
        "holder",
        "strap",
        "shopping",
        "accessories",
        "accessoire",
        "accessoires",
        "metis",
        "purse",
        "speedy",
        "city",
        "sunglasses",
        "charm",
        "diamonds",
        "diamond",
        "camera",
        "saddle",
        "baguette",
        "crossbody",
        "marmont",
        "bumbag",
        "triomphe",
        "shopper",
        "messenger",
        "cover",
        "book",
        "belt",
        "nano",
        "brooch",
        "gabrielle",
        "luggage",
        "boston",
        "ophidia",
        "bandeau",
        "sandals",
        "trunk",
        "pliage",
        "waist",
        "antigona",
        "loop",
        "boots",
        "cotton",
        "jumbo",
        "pendant",
        "zip",
        "box",
        "cassette",
        "puzzle",
        "croisette",
        "alma",
        "cabas",
        "noe",
        "gst",
        "tabby",
        "loulou",
        "bambino",
        "jackie",
        "hobo",
        "eva",
        "briefcase",
        "bucket",
        "kate",
        "handbag",
        "mahina",
        "pocket",
        "marcie",
        "organizer",
        "loafers",
        "knot",
        "set",
        "flat",
        "bandouliere",
        "sukey",
        "duffle",
        "padlock",
        "bowler",
        "papillon",
        "teen",
        "maxi",
        "twilly",
        "choker",
        "archive",
        "palais",
        "souple",
        "medusa",
        "clip",
        "envelope",
        "roseau",
        "minaudiere",
        "college",
        "mesh",
        "pumps",
        "tweed",
        "falabella",
        "compact",
        "lipstick",
        "tassel",
        "sicily",
        "pallas",
        "chapeau",
        "hirondelle",
        "taigarama",
        "malle",
        "trouville",
        "companion",
        "sufflette",
        "bowling",
        "bayswater",
        "galleria",
        "spike",
        "petite",
        "pearls",
        "shadow",
        "chevron",
        "soho",
        "montaigne",
        "looping",
        "paddington",
        "rockstud",
        "herbag",
        "hamilton",
        "chiquito",
        "mysore",
        "marelle",
        "monceau",
        "peekaboo",
        "uptown",
        "seau",
        "mezzo",
        "tivoli",
        "vanity",
        "woody",
        "sologne",
        "puffer",
        "espadrilles",
        "pico",
        "perforated",
        "artsy",
        "totally",
        "diorissimo",
        "houston",
        "picotin",
        "rodeo",
        "diaper",
        "guccissima",
        "marignan",
        "saumur",
        "cassandra",
        "luco",
        "naviglio",
        "jacket",
        "spazzolato",
        "swing",
        "snapshot",
        "paraty",
        "arcadie",
        "slides",
        "mombasa",
        "street",
        "pelham",
        "nodini",
        "niki",
        "onthego",
        "madison",
        "cleo",
        "drew",
        "serpenti",
        "interlocking",
        "capucines",
        "dior",
        "deauville",
        "dionysus",
        "giant",
        "jodie",
        "medallion",
        "basket",
        "abbey",
        "anjou",
        "casaque",
        "buckle",
        "toy",
        "perfect",
        "phantom",
        "saffiano",
        "andiamo",
        "victoire",
        "neonoe",
        "keepall",
        "constance",
        "bolide",
        "travel",
        "bag",
        "dior",
        # 材质 / 结构 / 五金（尾部高频但非色名）
        "flap",
        "handle",
        "woc",
        "caviar",
        "soft",
        "lambskin",
        "metal",
        "sterling",
        "tpm",
        "drawstring",
        "logo",
        "wool",
        "nylon",
        "denim",
        "crystal",
        "horsebit",
        "monogram",
        "quilted",
        "coated",
        "calfskin",
        "goatskin",
        "sheepskin",
        "python",
        "alligator",
        "crocodile",
        "viscose",
        "polyester",
        "polyamide",
        "fabric",
        "textile",
        "cloth",
        "resin",
        "ceramic",
        "plexiglass",
        "hardware",
        "stud",
        "studs",
        "studded",
        "spiked",
        "rhinestone",
        "crystals",
        "pearl",
        "pearls",
        "beads",
        "chain",
        "lock",
        "zip",
        "zipper",
        "clasp",
        "tag",
        "charm",
        "keychain",
        "headband",
        "scrunchie",
        "hatbox",
        "dustbag",
        "pochette",
        "card",
        "insert",
        "strap",
        "shoulder",
        "cross",
        "convertible",
        "adjustable",
        "reversible",
        "foldover",
        "zippered",
        "quilt",
        "jacquard",
        "satin",
        "velvet",
        "tweed",
        "knit",
        "mesh",
        "neoprene",
        "rubber",
        "vegan",
        "intrecciato",
        "guccissima",
        "microguccissima",
        "monogramme",
        "oblique",
        "gg",
        "cc",
        "damier",
        "empreinte",
        "vernis",
        "toile",
        "raffia",
        "wicker",
        "epsom",
        "togo",
        "swift",
        "box",
        "barenia",
        "evercolor",
        "vitello",
        "nubuck",
        "spazzolato",
        "grain",
        "grained",
        "smooth",
        "matte",
        "glossy",
        "glazed",
        "printed",
        "embroidered",
        "embellished",
        "applique",
        "perforated",
        "stitched",
        "whipstitch",
        "surpique",
        "padded",
        "pleated",
        "ruched",
        "braided",
        "woven",
        "striped",
        "stripes",
        "check",
        "plaid",
        "patch",
        "patches",
        "logo",
        "signature",
        "edition",
        "limited",
        "vintage",
        "archive",
        "regular",
        "classic",
        "mini",
        "micro",
        "small",
        "medium",
        "large",
        "maxi",
        "petit",
        "petite",
        "jumbo",
        "teen",
        "nano",
        "xxl",
        "xxs",
        "horizontal",
        "vertical",
        "wide",
        "long",
        "thin",
        "round",
        "square",
        "oval",
        "rectangular",
        "rectangle",
        "triangle",
        "asymmetric",
        "oversized",
        "compact",
        "slim",
        "flat",
        "tall",
        "deep",
        "high",
        "low",
        "open",
        "closed",
        "double",
        "single",
        "top",
        "front",
        "back",
        "side",
        "left",
        "right",
        "new",
        "used",
        "giftable",
        "excellent",
        "good",
        "fair",
        "worn",
        "travel",
        "shopping",
        "work",
        "business",
        "evening",
        "day",
        "night",
        "summer",
        "winter",
        "spring",
        "autumn",
        "sport",
        "sports",
        "sporty",
        "outdoor",
        "beach",
        "school",
        "office",
        "laptop",
        "phone",
        "makeup",
        "toiletry",
        "passport",
        "key",
        "card",
        "coin",
        "bill",
        "fold",
        "foldover",
        "bundle",
        "set",
        "kit",
        "case",
        "cover",
        "sleeve",
        "pouch",
        "wallet",
        "clutch",
        "tote",
        "satchel",
        "backpack",
        "duffel",
        "carryall",
        "carry",
        "shopper",
        "messenger",
        "crossbody",
        "shoulder",
        "handbag",
        "hobo",
        "bucket",
        "bowling",
        "boston",
        "speedy",
        "alma",
        "neverfull",
        "onthego",
        "capucines",
        "picotin",
        "herbag",
        "evelyne",
        "lindy",
        "bolide",
        "kelly",
        "birkin",
        "constance",
        "garden",
        "picnic",
        "inout",
        "keepall",
        "speedy",
        "papillon",
        "noe",
        "pochette",
        "metis",
        "onthego",
        "deauville",
        "dionysus",
        "marmont",
        "ophidia",
        "jackie",
        "bamboo",
        "horsebit",
        "sylvie",
        "diana",
        "padlock",
        "ophidia",
        "antigona",
        "puzzle",
        "loulou",
        "kate",
        "niki",
        "sac",
        "bag",
    }
)

# 修饰/纹理词：库内尾部常见，但不是专有色名
_SKIP_MODIFIER = frozenset(
    {
        "embossed",
        "printed",
        "aged",
        "washed",
        "reverse",
        "fluo",
        "neon",
        "electric",
        "electrique",
        "optic",
        "optical",
        "iridescent",
        "transparent",
        "translucent",
        "gradient",
        "degrade",
        "monochrome",
        "multicolor",
        "colorblock",
        "reversible",
        "convertible",
        "adjustable",
        "perfect",
        "classic",
        "iconic",
        "regular",
        "original",
        "vintage",
        "archive",
        "limited",
        "edition",
        "special",
        "collaboration",
        "animation",
        "christmas",
        "xmas",
        "holiday",
        "seasonal",
        "travel",
        "shopping",
        "accessoires",
        "accessories",
        "accessoire",
        "west",
        "east",
        "north",
        "south",
        "left",
        "right",
        "off",
        "on",
        "all",
        "the",
        "you",
        "day",
        "night",
        "time",
        "first",
        "last",
        "new",
        "old",
        "big",
        "baby",
        "toy",
        "heart",
        "flower",
        "flowers",
        "love",
        "joy",
        "star",
        "moon",
        "sun",
        "air",
        "water",
        "fire",
        "ice",
        "snow",
        "rain",
        "wind",
        "cloud",
        "cloudy",
        "storm",
        "fog",
        "hot",
        "warm",
        "cool",
        "cold",
        "fresh",
        "sweet",
        "sour",
        "bitter",
        "salty",
        "spicy",
        "bum",
        "web",
        "jour",
        "rock",
    }
)


def _lexicon_candidates(mined: Counter[str], existing: frozenset[str]) -> list[tuple[str, int]]:
    """从挖掘结果中筛出可写入色名词库的词条。"""
    out: list[tuple[str, int]] = []
    for word, count in mined.most_common():
        key = word.lower()
        if key in existing:
            continue
        if key in _SKIP_TAIL or key in _SKIP_MODIFIER:
            continue
        # Dark/Light/Pale 等单独作尾部色修饰词保留
        if key in {"dark", "light", "pale", "deep", "bright", "natural", "pastel", "dusty", "bright"}:
            out.append((word, count))
            continue
        # 全大写缩写（如 WOC）跳过
        if word.isupper() and len(word) <= 4:
            continue
        # 纯小写（travel 等）跳过
        if word.islower():
            continue
        out.append((word, count))
    return out

_TAIL_SQL = """
SELECT tail, SUM(cnt)::bigint AS total
FROM (
  SELECT split_part("{col}", ' ', array_length(string_to_array(trim("{col}"), ' '), 1)) AS tail,
         COUNT(*) AS cnt
  FROM "{table}"
  WHERE "{col}" IS NOT NULL AND trim("{col}") <> ''
  GROUP BY 1
) s
WHERE tail ~ '^[A-Za-z][A-Za-z]+$' AND length(tail) >= 3
GROUP BY tail
"""


def _mine_tail_tokens(min_count: int) -> Counter[str]:
    counts: Counter[str] = Counter()
    with db_session() as conn:
        with conn.cursor() as cur:
            cur.execute("SET statement_timeout = 120000")
            for table, col in (("F", "model"), ("R", "model"), ("V", "product_name")):
                cur.execute(_TAIL_SQL.format(table=table, col=col))
                for tail, total in cur.fetchall():
                    if _is_size_token(tail):
                        continue
                    if tail.lower() in _SKIP_TAIL:
                        continue
                    counts[tail] += int(total)
    return Counter({k: v for k, v in counts.items() if v >= min_count})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-count", type=int, default=8, help="尾部词最少出现次数（报告）")
    parser.add_argument("--lexicon-min-count", type=int, default=25, help="写入词库的最低频次")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    load_config()
    existing = luxury_color_lexicon()
    mined = _mine_tail_tokens(args.min_count)
    all_mined = [
        (word, mined[word])
        for word in sorted(mined, key=lambda w: (-mined[w], w.lower()))
        if word.lower() not in existing
    ]
    lexicon_rows = [(w, c) for w, c in _lexicon_candidates(mined, existing) if c >= args.lexicon_min_count]

    REPORT_PATH.write_text(
        "\n".join(
            [
                f"# 库内型号尾部词（F/R/V 合并，≥{args.min_count} 次，已排除包型/品类 skip 表）",
                f"# 共 {len(all_mined)} 个，不在现有 luxury_color_lexicon",
                "# word\tcount",
                *[f"{word}\t{count}" for word, count in all_mined],
                "",
                f"# --- 建议写入词库（再滤材质/修饰后 {len(lexicon_rows)} 个）---",
                "# word\tcount",
                *[f"{word}\t{count}" for word, count in lexicon_rows],
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"挖掘 {len(all_mined)} 个尾部词（min_count={args.min_count}）", flush=True)
    print(f"建议写入词库 {len(lexicon_rows)} 个:", flush=True)
    for word, count in lexicon_rows[:60]:
        print(f"  {word} ({count})", flush=True)
    if len(lexicon_rows) > 60:
        print(f"  ... 另有 {len(lexicon_rows) - 60} 个，见 {REPORT_PATH}", flush=True)
    else:
        print(f"完整列表见 {REPORT_PATH}", flush=True)

    if args.dry_run or not lexicon_rows:
        return 0

    new_words = [word for word, _ in lexicon_rows]
    with LEXICON_PATH.open("a", encoding="utf-8") as fh:
        fh.write("\n# --- auto-mined from F/R/V ---\n")
        for word in new_words:
            fh.write(f"{word}\n")
    print(f"已追加 {len(new_words)} 条到 {LEXICON_PATH}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
